/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

import fs from 'fs'
import path from 'path'
import { OFFICIAL_BASE_IMAGES, SERVICE_CATALOG } from './labBuilderConstants.js'
import { inferFileStage } from './labTemplateVariables.js'
import {
  labUsesRuntimeFilesystem,
  syncFilesystemFields,
  targetManifestFromLab
} from './labFilesystem.js'
import { generateDockerComposeYaml } from './labBuilderCompose.js'

const SHARED_SCRIPTS = [
  'apply-lab-credentials.sh',
  'configure-lab-ssh-access.sh',
  'start-lab-sshd.sh',
  'apply-lab-files.sh'
]

/**
 * @param {object} lab
 */
export function resolveBaseImage(lab) {
  const docker = lab.docker ?? {}
  if (docker.baseImageId) {
    const official = OFFICIAL_BASE_IMAGES.find((b) => b.id === docker.baseImageId)
    if (official) return official.image
  }
  if (docker.baseImage?.trim()) return docker.baseImage.trim()
  if (docker.imageSource === 'prebuilt' && docker.image?.trim()) return docker.image.trim()
  return 'ubuntu:22.04'
}

/**
 * @param {object} lab
 * @returns {string[]}
 */
export function collectPackages(lab) {
  const docker = lab.docker ?? {}
  /** @type {Set<string>} */
  const pkgs = new Set()
  for (const p of docker.packages ?? []) {
    if (typeof p === 'string' && p.trim()) pkgs.add(p.trim())
  }
  for (const svcId of docker.services ?? []) {
    const svc = SERVICE_CATALOG[svcId]
    if (svc?.packages) {
      for (const p of svc.packages) pkgs.add(p)
    }
  }
  if (!pkgs.size && (docker.services ?? []).includes('ssh')) {
    for (const p of SERVICE_CATALOG.ssh.packages) pkgs.add(p)
  }
  if ((docker.services ?? []).includes('ssh') || labHasSshPort(lab)) {
    for (const p of SERVICE_CATALOG.ssh.packages) pkgs.add(p)
  }
  const hasRuntimeManifest = labUsesRuntimeFilesystem(lab)
  if (hasRuntimeManifest) pkgs.add('python3')
  return [...pkgs].sort()
}

/**
 * @param {object} lab
 */
function labHasSshPort(lab) {
  return (lab.docker?.ports ?? []).some((p) => {
    const port = p.container ?? p.containerPort
    return port === 22 || p.purpose === 'ssh'
  })
}

/**
 * @param {object} lab
 */
export function buildFilesManifest(lab) {
  syncFilesystemFields(lab)
  return targetManifestFromLab(lab)
}

/**
 * @param {object} lab
 */
export function generateDockerfile(lab) {
  const base = resolveBaseImage(lab)
  const packages = collectPackages(lab)
  const ports = (lab.docker?.ports ?? [])
    .map((p) => p.container ?? p.containerPort)
    .filter((n) => Number.isFinite(n))
  const expose = [...new Set([22, ...ports])].sort((a, b) => a - b)

  const pkgRun =
    packages.length > 0
      ? `RUN apt-get update \\
  && apt-get install -y --no-install-recommends ${packages.join(' ')} \\
  && rm -rf /var/lib/apt/lists/*`
      : ''

  const lines = [
    `# Generated by Computer Server Labs Lab Builder`,
    `FROM ${base}`,
    'ENV DEBIAN_FRONTEND=noninteractive',
    pkgRun,
    'RUN mkdir -p /run/sshd /etc/sgq',
    ...SHARED_SCRIPTS.map((s) => `COPY common/${s} /usr/local/bin/${s}`),
    'COPY entrypoint.sh /usr/local/bin/sgq-entrypoint.sh',
    'COPY lab-files-manifest.json /etc/sgq/lab-files-manifest.json',
    'COPY files/ /tmp/sgq-build-files/',
    `RUN sed -i 's/\\r$//' /usr/local/bin/*.sh && chmod +x /usr/local/bin/sgq-entrypoint.sh /usr/local/bin/apply-lab-files.sh`,
    'RUN if [ -d /tmp/sgq-build-files ] && [ "$(ls -A /tmp/sgq-build-files 2>/dev/null)" ]; then \\',
    '      find /tmp/sgq-build-files -type f | while read -r f; do \\',
    '        rel="${f#/tmp/sgq-build-files}"; \\',
    '        dest="/${rel}"; \\',
    '        mkdir -p "$(dirname "$dest")"; \\',
    '        cp "$f" "$dest"; \\',
    '      done; \\',
    '    fi',
    ...expose.map((p) => `EXPOSE ${p}`),
    'ENTRYPOINT ["/usr/local/bin/sgq-entrypoint.sh"]'
  ].filter(Boolean)

  return `${lines.join('\n')}\n`
}

/**
 * @param {object} lab
 */
export function generateEntrypointSh(lab) {
  const services = lab.docker?.services ?? []
  const startup = lab.docker?.startupCommands ?? []
  const hasNginx = services.includes('nginx')
  const hasApache = services.includes('apache')
  const hasPythonHttp = services.includes('python-http')
  const hasCron = services.includes('cron')
  const sshService = services.includes('ssh') || labHasSshPort(lab)

  const lines = [
    '#!/bin/bash',
    '# Generated by Computer Server Labs Lab Builder',
    'set -euo pipefail',
    '',
    'SGQ_USER="${SGQ_USERNAME:-${LAB_USERNAME:-}}"',
    'SGQ_PASS="${SGQ_PASSWORD:-${LAB_PASSWORD:-}}"',
    'if [ -z "$SGQ_USER" ] || [ -z "$SGQ_PASS" ]; then',
    '  echo "entrypoint: SGQ_USERNAME and SGQ_PASSWORD must be set" >&2',
    '  exit 1',
    'fi',
    'export SGQ_USERNAME="$SGQ_USER" SGQ_PASSWORD="$SGQ_PASS" LAB_USERNAME="$SGQ_USER" LAB_PASSWORD="$SGQ_PASS"',
    '',
    '. /usr/local/bin/apply-lab-credentials.sh',
    'apply_lab_credentials',
    'configure_mission_sshd',
    '',
    'if [ "$SGQ_USER" = "root" ]; then export SGQ_LOGIN_DIR="/root" SGQ_LOGIN_USER="root"; else export SGQ_LOGIN_DIR="/home/$SGQ_USER" SGQ_LOGIN_USER="$SGQ_USER"; fi',
    '. /usr/local/bin/apply-lab-files.sh',
    'apply_lab_files || { echo "entrypoint: apply_lab_files failed" >&2; exit 1; }',
    ''
  ]

  if (hasCron) {
    lines.push('cron || service cron start || true', '')
  }

  for (const cmd of startup) {
    if (!cmd?.command) continue
    const runAs = cmd.runAs === 'lab-user' ? '"$SGQ_USER"' : 'root'
    const when = cmd.when === 'before-ssh' ? 'before-ssh' : 'before-ssh'
    lines.push(`# startup: ${cmd.label ?? cmd.command} (${when}, as ${runAs})`)
    if (runAs === 'root') {
      lines.push(cmd.command)
    } else {
      lines.push(`su -s /bin/bash -c ${JSON.stringify(cmd.command)} "$SGQ_USER"`)
    }
    lines.push('')
  }

  if (hasNginx) {
    lines.push('mkdir -p /var/www/html', 'nginx || nginx -g "daemon off;" &', '')
  }
  if (hasApache) {
    lines.push('mkdir -p /var/www/html', 'apache2ctl start || service apache2 start || true', '')
  }
  if (hasPythonHttp) {
    lines.push('mkdir -p /var/www/html', 'python3 -m http.server 8000 --directory /var/www/html &', '')
  }

  lines.push('if [ -x /usr/local/bin/lab-setup.sh ]; then', '  /usr/local/bin/lab-setup.sh', 'fi', '')

  if (sshService) {
    lines.push('. /usr/local/bin/start-lab-sshd.sh', 'start_lab_sshd')
  } else if (hasNginx) {
    lines.push('exec nginx -g "daemon off;"')
  } else if (hasApache) {
    lines.push('exec apache2ctl -D FOREGROUND')
  } else {
    lines.push('echo "entrypoint: no foreground service; sleeping"', 'exec sleep infinity')
  }

  return `${lines.join('\n')}\n`
}

/**
 * Materialize build-time files under draftRoot/files/
 * @param {string} draftRoot
 * @param {object} lab
 */
export function materializeBuildFiles(draftRoot, lab) {
  const filesDir = path.join(draftRoot, 'files')
  fs.rmSync(filesDir, { recursive: true, force: true })
  fs.mkdirSync(filesDir, { recursive: true })

  const synced = { ...lab }
  syncFilesystemFields(synced)
  for (const entry of synced.filesystem?.target?.files ?? []) {
    if (inferFileStage(entry) !== 'build') continue
    const rel = String(entry.path ?? '').replace(/^\//, '')
    if (!rel) continue
    const dest = path.join(filesDir, rel)
    fs.mkdirSync(path.dirname(dest), { recursive: true })
    fs.writeFileSync(dest, entry.content ?? '', 'utf8')
  }
}

/**
 * Copy shared scripts from repo labs/common into draft common/
 * @param {string} draftRoot
 * @param {string} repoLabsCommon
 */
export function syncCommonScripts(draftRoot, repoLabsCommon) {
  const commonDir = path.join(draftRoot, 'common')
  fs.mkdirSync(commonDir, { recursive: true })
  for (const name of SHARED_SCRIPTS) {
    const src = path.join(repoLabsCommon, name)
    if (fs.existsSync(src)) {
      fs.copyFileSync(src, path.join(commonDir, name))
    }
  }
}

/**
 * @param {object} lab
 * @param {string} draftRoot
 * @param {string} repoLabsCommon
 */
export function syncGeneratedDraftArtifacts(lab, draftRoot, repoLabsCommon) {
  const useGenerated = lab.docker?.builderGenerated === true || lab.docker?.imageSource === 'local-build'
  if (!useGenerated && lab.docker?.imageSource === 'prebuilt') {
    return { generated: false }
  }

  syncCommonScripts(draftRoot, repoLabsCommon)
  materializeBuildFiles(draftRoot, lab)

  const manifest = buildFilesManifest(lab)
  fs.writeFileSync(path.join(draftRoot, 'lab-files-manifest.json'), JSON.stringify(manifest, null, 2), 'utf8')

  const dockerfile = generateDockerfile(lab)
  const entrypoint = generateEntrypointSh(lab)
  fs.writeFileSync(path.join(draftRoot, 'Dockerfile'), dockerfile, 'utf8')
  fs.writeFileSync(path.join(draftRoot, 'entrypoint.sh'), entrypoint, 'utf8')

  const compose = generateDockerComposeYaml(lab)
  const composePath = path.join(draftRoot, 'docker-compose.yml')
  if (compose) {
    fs.writeFileSync(composePath, compose, 'utf8')
  } else if (fs.existsSync(composePath)) {
    fs.rmSync(composePath, { force: true })
  }

  if (!lab.docker) lab.docker = {}
  if (!lab.docker.image?.trim()) {
    lab.docker.image = `sysadmin-game/${lab.id}:latest`
  }
  lab.docker.imageSource = lab.docker.imageSource ?? 'local-build'
  lab.docker.buildPath = lab.docker.buildPath ?? '.'
  lab.docker.builderGenerated = true

  return { generated: true, dockerfile, entrypoint, manifest }
}

/**
 * @param {object} lab
 */
export function applyMockWebsiteTemplate(lab) {
  const next = { ...lab }
  next.docker = {
    ...(next.docker ?? {}),
    baseImageId: 'ubuntu-22.04',
    builderGenerated: true,
    imageSource: 'local-build',
    buildPath: '.',
    services: [...new Set([...(next.docker?.services ?? []), 'ssh', 'nginx'])],
    packages: [...new Set([...(next.docker?.packages ?? [])])]
  }
  next.files = [
    ...(next.files ?? []).filter((f) => f.path !== '/var/www/html/index.html'),
    {
      path: '/var/www/html/index.html',
      content: '<!DOCTYPE html>\n<html><head><title>Broken Web App</title></head>\n<body><h1>Broken Web App</h1><p>Fix the web server configuration.</p></body></html>\n',
      owner: 'root',
      group: 'root',
      mode: '0644',
      stage: 'build'
    }
  ]
  next.directories = [
    ...(next.directories ?? []).filter((d) => d.path !== '/var/www/html'),
    { path: '/var/www/html', owner: 'root', group: 'root', mode: '0755', stage: 'build' }
  ]
  const ports = next.docker.ports ?? []
  if (!ports.some((p) => (p.container ?? p.containerPort) === 80)) {
    ports.push({
      containerPort: 80,
      protocol: 'tcp',
      purpose: 'web',
      label: 'Web Service',
      exposeToHost: true,
      showToUser: true
    })
  }
  next.docker.ports = ports
  return next
}
