/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

import fs from 'fs'
import path from 'path'
import { OFFICIAL_BASE_IMAGES } from './labBuilderConstants.js'
import { inferFileStage } from './labTemplateVariables.js'
import { syncFilesystemFields, workstationManifestFromLab } from './labFilesystem.js'
import { resolveCustomWorkstationImageTag } from '../workstation/workstationCustomProfile.js'

const WS_SHARED_SCRIPTS = ['apply-lab-files.sh']

const DEFAULT_LINUX_WS_PACKAGES = [
  'bash',
  'openssh-client',
  'sshpass',
  'curl',
  'wget',
  'nano',
  'vim-tiny',
  'less',
  'grep',
  'iproute2',
  'netcat-openbsd',
  'dnsutils',
  'procps',
  'sudo',
  'ca-certificates',
  'python3'
]

/**
 * @param {object} lab
 */
export function resolveWorkstationBaseImage(lab) {
  const custom = lab.workstation?.custom ?? {}
  if (custom.baseImageId) {
    const official = OFFICIAL_BASE_IMAGES.find((b) => b.id === custom.baseImageId)
    if (official) return official.image
  }
  if (custom.baseImage?.trim()) return custom.baseImage.trim()
  if (custom.runtime === 'windows') {
    return 'mcr.microsoft.com/windows/servercore:ltsc2022-amd64'
  }
  return 'ubuntu:22.04'
}

/**
 * @param {object} lab
 */
export function collectWorkstationPackages(lab) {
  const custom = lab.workstation?.custom ?? {}
  const pkgs = new Set(DEFAULT_LINUX_WS_PACKAGES)
  for (const p of custom.packages ?? []) {
    if (typeof p === 'string' && p.trim()) pkgs.add(p.trim())
  }
  const wsFiles = lab.filesystem?.workstation?.files ?? custom.files ?? []
  const hasRuntimeFiles = wsFiles.some((f) => inferFileStage(f) === 'runtime')
  if (hasRuntimeFiles) pkgs.add('python3')
  return [...pkgs].sort()
}

/**
 * @param {object} lab
 */
export function buildWorkstationFilesManifest(lab) {
  syncFilesystemFields(lab)
  return workstationManifestFromLab(lab)
}

/**
 * @param {object} lab
 */
export function generateWorkstationDockerfile(lab) {
  const custom = lab.workstation?.custom ?? {}
  if (custom.runtime === 'windows') {
    return generateWindowsWorkstationDockerfile(lab)
  }

  const base = resolveWorkstationBaseImage(lab)
  const packages = collectWorkstationPackages(lab)
  const tag = resolveCustomWorkstationImageTag(lab)

  const lines = [
    '# Generated by Computer Server Labs Lab Builder — custom workstation',
    `FROM ${base}`,
    'ENV DEBIAN_FRONTEND=noninteractive',
    `ENV SGQ_WORKSTATION_LABEL="${(custom.name ?? 'Custom Lab Workstation').replace(/"/g, '')}"`,
    'ENV SGQ_WORKSTATION_SHELL=/bin/bash',
    `RUN apt-get update && apt-get install -y --no-install-recommends ${packages.join(' ')} && rm -rf /var/lib/apt/lists/*`,
    'RUN ln -sf /usr/bin/vim.tiny /usr/bin/vim 2>/dev/null || true',
    'RUN mkdir -p /etc/sgq',
    ...WS_SHARED_SCRIPTS.map((s) => `COPY common/${s} /usr/local/bin/${s}`),
    'COPY entrypoint.sh /entrypoint.sh',
    'COPY workstation-files-manifest.json /etc/sgq/workstation-files-manifest.json',
    'COPY files/ /tmp/sgq-ws-build-files/',
    `RUN sed -i 's/\\r$//' /entrypoint.sh /usr/local/bin/*.sh && chmod +x /entrypoint.sh /usr/local/bin/apply-lab-files.sh`,
    'RUN if [ -d /tmp/sgq-ws-build-files ] && [ "$(ls -A /tmp/sgq-ws-build-files 2>/dev/null)" ]; then \\',
    '      find /tmp/sgq-ws-build-files -type f | while read -r f; do \\',
    '        rel="${f#/tmp/sgq-ws-build-files}"; dest="/${rel}"; mkdir -p "$(dirname "$dest")"; cp "$f" "$dest"; \\',
    '      done; fi',
    'LABEL sgq.workstation.profile="custom"',
    `LABEL sgq.workstation.image="${tag}"`,
    'ENTRYPOINT ["/entrypoint.sh"]'
  ]
  return `${lines.join('\n')}\n`
}

/**
 * @param {object} lab
 */
function generateWindowsWorkstationDockerfile(lab) {
  const custom = lab.workstation?.custom ?? {}
  const base = resolveWorkstationBaseImage(lab)
  const tag = resolveCustomWorkstationImageTag(lab)
  return `# Generated by Computer Server Labs Lab Builder — custom Windows workstation
FROM ${base}
ENV SGQ_WORKSTATION_LABEL="${(custom.name ?? 'Custom Lab Workstation').replace(/"/g, '')}"
COPY entrypoint.ps1 C:\\\\entrypoint.ps1
LABEL sgq.workstation.profile="custom"
LABEL sgq.workstation.image="${tag}"
ENTRYPOINT ["powershell.exe", "-NoLogo", "-NoProfile", "-File", "C:\\\\entrypoint.ps1"]
`
}

/**
 * @param {object} lab
 */
export function generateWorkstationEntrypointSh(lab) {
  const custom = lab.workstation?.custom ?? {}
  const startupMessage =
    custom.startupMessage?.trim() ||
    'Use this workstation to investigate the lab target. Files here are for your investigation only.'

  return `#!/bin/bash
# Generated custom workstation entrypoint
set -euo pipefail

USERNAME="\${SGQ_USERNAME:-\${LAB_USERNAME:-user}}"
if [ "$USERNAME" = "root" ]; then
  echo "Custom workstation cannot run as root" >&2
  exit 1
fi
HOSTNAME="\${LAB_HOSTNAME:-lab-workstation}"
HOME_DIR="/home/\${USERNAME}"
TARGET_IP="\${SGQ_TARGET_INTERNAL_IP:-}"
TARGET_HOST="\${SGQ_TARGET_HOST:-lab-target}"
TARGET_SSH_PORT="\${SGQ_TARGET_SSH_PORT:-22}"

hostname "\${HOSTNAME}" 2>/dev/null || true

if ! id "$USERNAME" >/dev/null 2>&1; then
  useradd -m -s /bin/bash -d "$HOME_DIR" "$USERNAME"
fi
mkdir -p "$HOME_DIR"
chown "\${USERNAME}:\${USERNAME}" "$HOME_DIR"

if [ ! -f /etc/sudoers.d/lab-workstation ]; then
  echo "\${USERNAME} ALL=(ALL) NOPASSWD:ALL" >/etc/sudoers.d/lab-workstation
  chmod 440 /etc/sudoers.d/lab-workstation
fi

cat >/etc/motd <<MOTD
Computer Server Labs — Custom Lab Workstation
${startupMessage.replace(/\n/g, '\n')}
Target: ssh \${USERNAME}@\${TARGET_HOST} (port \${TARGET_SSH_PORT})
MOTD

export TARGET_HOST TARGET_IP TARGET_SSH_PORT
export SGQ_TARGET_HOST="$TARGET_HOST"
export SGQ_TARGET_INTERNAL_IP="$TARGET_IP"

if [ -f /usr/local/bin/apply-lab-files.sh ]; then
  # shellcheck source=/dev/null
  . /usr/local/bin/apply-lab-files.sh
  apply_lab_files /etc/sgq/workstation-files-manifest.json || {
    echo "workstation entrypoint: apply_lab_files failed" >&2
    exit 1
  }
fi

cat >"\${HOME_DIR}/.bashrc" <<'EOF'
export PS1='\\u@\\h:\\w\\$ '
if [ -f /etc/motd ] && [ -z "\${SGQ_MOTD_SHOWN:-}" ]; then
  export SGQ_MOTD_SHOWN=1
  cat /etc/motd
fi
cd "\${HOME}" 2>/dev/null || true
EOF
chown "\${USERNAME}:\${USERNAME}" "\${HOME_DIR}/.bashrc"

mkdir -p "\${HOME_DIR}/.ssh"
chmod 700 "\${HOME_DIR}/.ssh"
cat >"\${HOME_DIR}/.ssh/config" <<CFG
Host lab-target
  HostName \${TARGET_HOST}
  User \${USERNAME}
  Port \${TARGET_SSH_PORT}
  PreferredAuthentications password
  PubkeyAuthentication no
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
CFG
if [ -n "$TARGET_IP" ]; then
  cat >>"\${HOME_DIR}/.ssh/config" <<CFG

Host lab-target-ip
  HostName \${TARGET_IP}
  User \${USERNAME}
  Port \${TARGET_SSH_PORT}
  PreferredAuthentications password
  PubkeyAuthentication no
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
CFG
fi
chmod 600 "\${HOME_DIR}/.ssh/config"
chown -R "\${USERNAME}:\${USERNAME}" "\${HOME_DIR}/.ssh"

exec tail -f /dev/null
`
}

/**
 * @param {string} wsRoot
 * @param {object} lab
 */
export function materializeWorkstationBuildFiles(wsRoot, lab) {
  const custom = lab.workstation?.custom ?? {}
  const filesDir = path.join(wsRoot, 'files')
  fs.rmSync(filesDir, { recursive: true, force: true })
  fs.mkdirSync(filesDir, { recursive: true })
  const synced = { ...lab }
  syncFilesystemFields(synced)
  const wsFiles = synced.filesystem?.workstation?.files ?? []
  for (const entry of wsFiles) {
    if (inferFileStage(entry) !== 'build') continue
    const rel = String(entry.path ?? '').replace(/^\//, '')
    if (!rel) continue
    const dest = path.join(filesDir, rel)
    fs.mkdirSync(path.dirname(dest), { recursive: true })
    fs.writeFileSync(dest, entry.content ?? '', 'utf8')
  }
}

/**
 * @param {string} wsRoot
 * @param {string} repoCommon
 */
export function syncWorkstationCommonScripts(wsRoot, repoCommon) {
  const commonDir = path.join(wsRoot, 'common')
  fs.mkdirSync(commonDir, { recursive: true })
  for (const name of WS_SHARED_SCRIPTS) {
    const src = path.join(repoCommon, name)
    if (fs.existsSync(src)) fs.copyFileSync(src, path.join(commonDir, name))
  }
}

/**
 * @param {object} lab
 * @param {string} draftRoot
 * @param {string} repoCommon
 */
export function syncGeneratedWorkstationArtifacts(lab, draftRoot, repoCommon) {
  const custom = lab.workstation?.custom
  if (!custom?.enabled) return { generated: false }

  const wsRoot = path.join(draftRoot, 'workstation')
  fs.mkdirSync(wsRoot, { recursive: true })

  syncWorkstationCommonScripts(wsRoot, repoCommon)
  materializeWorkstationBuildFiles(wsRoot, lab)

  const manifest = buildWorkstationFilesManifest(lab)
  fs.writeFileSync(path.join(wsRoot, 'workstation-files-manifest.json'), JSON.stringify(manifest, null, 2), 'utf8')

  const dockerfile = generateWorkstationDockerfile(lab)
  const entrypoint =
    custom.runtime === 'windows'
      ? '# Windows custom workstation — extend entrypoint.ps1 manually if needed\n'
      : generateWorkstationEntrypointSh(lab)

  fs.writeFileSync(path.join(wsRoot, 'Dockerfile'), dockerfile, 'utf8')
  if (custom.runtime !== 'windows') {
    fs.writeFileSync(path.join(wsRoot, 'entrypoint.sh'), entrypoint, 'utf8')
  }

  if (!lab.workstation) lab.workstation = {}
  lab.workstation.custom = { ...custom, sourceType: custom.sourceType ?? 'generated' }

  return { generated: true, dockerfile, entrypoint, manifest, wsRoot }
}
