/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

/**
 * @param {object} lab
 */
export function labUsesComposeLayout(lab) {
  return lab?.docker?.layout === 'compose' || (lab?.docker?.composeServices?.length ?? 0) > 1
}

/**
 * @param {object} lab
 * @returns {object[]}
 */
export function normalizeComposeServices(lab) {
  const labId = lab.id ?? 'lab'
  const existing = lab.docker?.composeServices
  if (Array.isArray(existing) && existing.length > 0) {
    return existing.map((svc, i) => ({
      id: svc.id ?? `service-${i + 1}`,
      name: svc.name ?? svc.id ?? `service-${i + 1}`,
      image: svc.image ?? `sysadmin-game/${labId}-${svc.id ?? i}:latest`,
      build: svc.build ?? { context: svc.buildContext ?? `.`, dockerfile: svc.dockerfile ?? 'Dockerfile' },
      ports: svc.ports ?? [],
      primary: svc.primary === true
    }))
  }
  return [
    {
      id: 'target',
      name: 'target',
      image: lab.docker?.image ?? `sysadmin-game/${labId}:latest`,
      build: { context: '.', dockerfile: 'Dockerfile' },
      ports: lab.docker?.ports ?? [],
      primary: true
    }
  ]
}

/**
 * @param {object} lab
 */
export function generateDockerComposeYaml(lab) {
  if (!labUsesComposeLayout(lab)) return null

  const services = normalizeComposeServices(lab)
  const lines = [
    '# Generated by Computer Server Labs Lab Builder',
    'services:'
  ]

  for (const svc of services) {
    lines.push(`  ${svc.name}:`)
    if (svc.build) {
      lines.push(`    build:`)
      lines.push(`      context: ${svc.build.context ?? '.'}`)
      lines.push(`      dockerfile: ${svc.build.dockerfile ?? 'Dockerfile'}`)
    } else if (svc.image) {
      lines.push(`    image: ${svc.image}`)
    }
    const portMappings = (svc.ports ?? [])
      .filter((p) => p.exposeToHost === true)
      .map((p) => {
        const container = p.container ?? p.containerPort
        return `"127.0.0.1:${container}:${container}"`
      })
    if (portMappings.length) {
      lines.push(`    ports:`)
      for (const pm of portMappings) {
        lines.push(`      - ${pm}`)
      }
    }
    if (svc.primary) {
      lines.push(`    hostname: lab-target`)
    }
    lines.push(`    networks:`)
    lines.push(`      sgq_session:`)
    const alias = svc.primary ? 'lab-target' : svc.name
    lines.push(`        aliases:`)
    lines.push(`          - ${alias}`)
  }

  lines.push('')
  lines.push('networks:')
  lines.push('  sgq_session:')
  lines.push('    external: true')
  lines.push('    name: sysadmin-game-net-<sessionId>')

  return `${lines.join('\n')}\n`
}
